// <auto-generated />
using System;
using GearGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearGo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921042918_UpdateTask7Entities")]
    partial class UpdateTask7Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietDonThue", b =>
                {
                    b.Property<long>("MaChiTietDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_don");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaChiTietDon"));

                    b.Property<decimal>("DonGiaThueMoiNgay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia_thue_moi_ngay");

                    b.Property<long?>("DonThueMaDonThue")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GiaTriBoiThuongMoiThietBi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri_boi_thuong_moi_thiet_bi");

                    b.Property<long>("MaDonThue")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_don_thue");

                    b.Property<long>("MaSanPham")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    b.Property<decimal>("MucCocMoiThietBi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("muc_coc_moi_thiet_bi");

                    b.Property<string>("PhuKienVaMucBoiThuongLucDat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phu_kien_va_muc_boi_thuong_luc_dat");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<int>("SoNgayTinhTien")
                        .HasColumnType("int")
                        .HasColumnName("so_ngay_tinh_tien");

                    b.Property<string>("TenSanPhamLucDat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_san_pham_luc_dat");

                    b.Property<decimal>("TienGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_giam");

                    b.HasKey("MaChiTietDon");

                    b.HasIndex("DonThueMaDonThue");

                    b.HasIndex("MaDonThue");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_DON_THUE");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietGioThue", b =>
                {
                    b.Property<long>("MaChiTietGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_gio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaChiTietGio"));

                    b.Property<long>("MaGioThue")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_gio_thue");

                    b.Property<long>("MaSanPham")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTietGio");

                    b.HasIndex("MaGioThue");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_GIO_THUE");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<long>("MaChiTietPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_phieu_nhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaChiTietPhieuNhap"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia_nhap");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<long>("MaPhieuNhap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_phieu_nhap");

                    b.Property<long>("MaSanPham")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<string>("TenSanPhamLucNhap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_san_pham_luc_nhap");

                    b.Property<string>("TinhTrangKhiNhap")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tinh_trang_khi_nhap");

                    b.HasKey("MaChiTietPhieuNhap");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_PHIEU_NHAP");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChinhSach", b =>
                {
                    b.Property<long>("MaChinhSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chinh_sach");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaChinhSach"));

                    b.Property<long>("MaNguoiTao")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nguoi_tao");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NoiDungChinhSach")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_chinh_sach");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int")
                        .HasColumnName("phien_ban");

                    b.Property<string>("TenChinhSach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_chinh_sach");

                    b.Property<DateTime>("ThoiDiemApDung")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_ap_dung");

                    b.HasKey("MaChinhSach");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("PhienBan")
                        .IsUnique();

                    b.ToTable("CHINH_SACH");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DanhMucSanPham", b =>
                {
                    b.Property<long>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_danh_muc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaDanhMuc"));

                    b.Property<long?>("MaDanhMucCha")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_danh_muc_cha");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_danh_muc");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu_hien_thi");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("MaDanhMucCha");

                    b.ToTable("DANH_MUC_SAN_PHAM");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DonThue", b =>
                {
                    b.Property<long>("MaDonThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_don_thue");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaDonThue"));

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email_lien_he");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime>("GioNhanDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_nhan_du_kien");

                    b.Property<DateTime>("GioTraDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_tra_du_kien");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime2")
                        .HasColumnName("han_thanh_toan");

                    b.Property<string>("KhuyenMaiLucDat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("khuyen_mai_luc_dat");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do_huy");

                    b.Property<long>("MaChinhSach")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chinh_sach");

                    b.Property<string>("MaDonHienThi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_don_hien_thi");

                    b.Property<long>("MaKhachHang")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khach_hang");

                    b.Property<long?>("MaNguoiHuy")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nguoi_huy");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dat");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai_nguoi_nhan");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nguoi_nhan");

                    b.Property<DateTime?>("ThoiDiemHoanTat")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_hoan_tat");

                    b.Property<DateTime?>("ThoiDiemHuy")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_huy");

                    b.Property<decimal>("TienThueGiuLaiKhiHuy")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue_giu_lai_khi_huy");

                    b.Property<decimal>("TongTienCoc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien_coc");

                    b.Property<decimal>("TongTienGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien_giam");

                    b.Property<decimal>("TongTienThueTruocGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien_thue_truoc_giam");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDonThue");

                    b.HasIndex("MaChinhSach");

                    b.HasIndex("MaDonHienThi")
                        .IsUnique();

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiHuy");

                    b.ToTable("DON_THUE");
                });

            modelBuilder.Entity("GearGo.Models.Entities.GioThue", b =>
                {
                    b.Property<long>("MaGioThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_gio_thue");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaGioThue"));

                    b.Property<DateTime?>("GioNhanDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_nhan_du_kien");

                    b.Property<DateTime?>("GioTraDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_tra_du_kien");

                    b.Property<long>("MaKhachHang")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khach_hang");

                    b.Property<long?>("MaKhuyenMai")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khuyen_mai");

                    b.HasKey("MaGioThue");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.ToTable("GIO_THUE");
                });

            modelBuilder.Entity("GearGo.Models.Entities.GiuCho", b =>
                {
                    b.Property<long>("MaGiuCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_giu_cho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaGiuCho"));

                    b.Property<long>("MaChiTietDon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_don");

                    b.Property<DateTime?>("ThoiDiemGiaiPhong")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_giai_phong");

                    b.Property<DateTime>("ThoiDiemHetHan")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_het_han");

                    b.Property<DateTime>("ThoiDiemTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_tao");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaGiuCho");

                    b.HasIndex("MaChiTietDon")
                        .IsUnique();

                    b.ToTable("GIU_CHO");
                });

            modelBuilder.Entity("GearGo.Models.Entities.HinhAnhSanPham", b =>
                {
                    b.Property<long>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_hinh_anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit")
                        .HasColumnName("la_anh_chinh");

                    b.Property<long>("MaSanPham")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HINH_ANH_SAN_PHAM");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhachHang", b =>
                {
                    b.Property<long>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khach_hang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaKhachHang"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<long>("MaTaiKhoan")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_tai_khoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<long>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khuyen_mai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaKhuyenMai"));

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri_giam");

                    b.Property<int?>("GioiHanMoiKhach")
                        .HasColumnType("int")
                        .HasColumnName("gioi_han_moi_khach");

                    b.Property<int>("LoaiGiam")
                        .HasColumnType("int")
                        .HasColumnName("loai_giam");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giam_gia");

                    b.Property<decimal?>("MucGiamToiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("muc_giam_toi_da");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int>("PhamVi")
                        .HasColumnType("int")
                        .HasColumnName("pham_vi_ap_dung");

                    b.Property<decimal>("TienThueToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue_toi_thieu");

                    b.Property<int?>("TongLuotSuDung")
                        .HasColumnType("int")
                        .HasColumnName("tong_luot_su_dung");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.ToTable("KHUYEN_MAI");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMaiDanhMuc", b =>
                {
                    b.Property<long>("MaKhuyenMai")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khuyen_mai");

                    b.Property<long>("MaDanhMuc")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_danh_muc");

                    b.HasKey("MaKhuyenMai", "MaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("KHUYEN_MAI_DANH_MUC");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMaiSanPham", b =>
                {
                    b.Property<long>("MaKhuyenMai")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khuyen_mai");

                    b.Property<long>("MaSanPham")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    b.HasKey("MaKhuyenMai", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KHUYEN_MAI_SAN_PHAM");
                });

            modelBuilder.Entity("GearGo.Models.Entities.LichSuTrangThaiDon", b =>
                {
                    b.Property<long>("MaLichSuDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_lich_su_don");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLichSuDon"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do");

                    b.Property<long>("MaDonThue")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_don_thue");

                    b.Property<long?>("MaNguoiThucHien")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nguoi_thuc_hien");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem");

                    b.Property<string>("TrangThaiSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai_sau");

                    b.Property<string>("TrangThaiTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai_truoc");

                    b.HasKey("MaLichSuDon");

                    b.HasIndex("MaDonThue");

                    b.HasIndex("MaNguoiThucHien");

                    b.ToTable("LICH_SU_TRANG_THAI_DON");
                });

            modelBuilder.Entity("GearGo.Models.Entities.LuotSuDungKhuyenMai", b =>
                {
                    b.Property<long>("MaLuotSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_luot_su_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLuotSuDung"));

                    b.Property<long>("MaDonThue")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_don_thue");

                    b.Property<long>("MaKhuyenMai")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_khuyen_mai");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien_giam");

                    b.Property<DateTime?>("ThoiDiemGiaiPhong")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_giai_phong");

                    b.Property<DateTime>("ThoiDiemGiuLuot")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_giu_luot");

                    b.Property<DateTime>("ThoiDiemHetHan")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_het_han");

                    b.Property<DateTime?>("ThoiDiemSuDung")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem_su_dung");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLuotSuDung");

                    b.HasIndex("MaDonThue")
                        .IsUnique();

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("LUOT_SU_DUNG_KHUYEN_MAI");
                });

            modelBuilder.Entity("GearGo.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<long>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nha_cung_cap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("MaNhaCungCapHienThi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_nha_cung_cap_hien_thi");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_so_thue");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoi_lien_he");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nha_cung_cap");

                    b.Property<bool>("TrangThaiHopTac")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai_hop_tac");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("MaNhaCungCapHienThi")
                        .IsUnique();

                    b.ToTable("NHA_CUNG_CAP");
                });

            modelBuilder.Entity("GearGo.Models.Entities.NhanVien", b =>
                {
                    b.Property<long>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nhan_vien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<long>("MaTaiKhoan")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_tai_khoan");

                    b.Property<DateOnly?>("NgayNghiViec")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nghi_viec");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.Property<string>("TrangThaiLamViec")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai_lam_viec");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("NHAN_VIEN");
                });

            modelBuilder.Entity("GearGo.Models.Entities.PhanCongThietBi", b =>
                {
                    b.Property<long>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_phan_cong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaPhanCong"));

                    b.Property<long>("MaChiTietDon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_don");

                    b.Property<long?>("MaNhanVienHuy")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nhan_vien_huy");

                    b.Property<long>("MaNhanVienPhanCong")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nhan_vien_phan_cong");

                    b.Property<long>("MaThietBi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_thiet_bi");

                    b.Property<DateTime?>("ThoiGianHuy")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_huy");

                    b.Property<DateTime>("ThoiGianPhanCong")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_phan_cong");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaChiTietDon");

                    b.HasIndex("MaNhanVienHuy");

                    b.HasIndex("MaNhanVienPhanCong");

                    b.HasIndex("MaThietBi");

                    b.ToTable("PHAN_CONG_THIET_BI");
                });

            modelBuilder.Entity("GearGo.Models.Entities.PhieuNhapHang", b =>
                {
                    b.Property<long>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_phieu_nhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do_huy");

                    b.Property<long>("MaNguoiLap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nguoi_lap");

                    b.Property<long?>("MaNguoiXacNhan")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nguoi_xac_nhan");

                    b.Property<long>("MaNhaCungCap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nha_cung_cap");

                    b.Property<string>("MaPhieuHienThi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_phieu_hien_thi");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_lap");

                    b.Property<DateTime?>("NgayNhapDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap_du_kien");

                    b.Property<DateTime?>("NgayNhapThucTe")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap_thuc_te");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_xac_nhan");

                    b.Property<string>("SoChungTuNhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("so_chung_tu_nha_cung_cap");

                    b.Property<string>("TenNguoiLapLucNhap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nguoi_lap_luc_nhap");

                    b.Property<string>("TenNguoiXacNhanLucNhap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nguoi_xac_nhan_luc_nhap");

                    b.Property<string>("ThongTinNhaCungCapLucNhap")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thong_tin_nha_cung_cap_luc_nhap");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNguoiLap");

                    b.HasIndex("MaNguoiXacNhan");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaPhieuHienThi")
                        .IsUnique();

                    b.ToTable("PHIEU_NHAP_HANG");
                });

            modelBuilder.Entity("GearGo.Models.Entities.SanPham", b =>
                {
                    b.Property<long>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_san_pham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaSanPham"));

                    b.Property<decimal>("GiaThueMoiNgay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_thue_moi_ngay");

                    b.Property<decimal>("GiaTriBoiThuong")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri_boi_thuong");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kich_thuoc");

                    b.Property<long>("MaDanhMuc")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_danh_muc");

                    b.Property<string>("MaSanPhamHienThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_san_pham_hien_thi");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<decimal>("MucCocMoiThietBi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("muc_coc_moi_thiet_bi");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_san_pham");

                    b.Property<string>("ThongSo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thong_so");

                    b.Property<string>("ThuongHieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thuong_hieu");

                    b.Property<string>("TrangThaiKinhDoanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai_kinh_doanh");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaSanPhamHienThi")
                        .IsUnique();

                    b.ToTable("SAN_PHAM");
                });

            modelBuilder.Entity("GearGo.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<long>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_tai_khoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LyDoKhoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do_khoa");

                    b.Property<string>("MatKhauBam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau_bam");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[so_dien_thoai] IS NOT NULL");

                    b.ToTable("TAI_KHOAN");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ThietBi", b =>
                {
                    b.Property<long>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ma_thiet_bi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaThietBi"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_nhap");

                    b.Property<long>("MaChiTietPhieuNhap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_chi_tiet_phieu_nhap");

                    b.Property<string>("MaThietBiHienThi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_thiet_bi_hien_thi");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap");

                    b.Property<string>("PhuKienDiKem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phu_kien_di_kem");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tinh_trang");

                    b.Property<int>("TrangThaiSuDung")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai_su_dung");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaChiTietPhieuNhap");

                    b.HasIndex("MaThietBiHienThi")
                        .IsUnique();

                    b.ToTable("THIET_BI");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietDonThue", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DonThue", null)
                        .WithMany("ChiTietDonThues")
                        .HasForeignKey("DonThueMaDonThue");

                    b.HasOne("GearGo.Models.Entities.DonThue", "DonThue")
                        .WithMany()
                        .HasForeignKey("MaDonThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonThue");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietGioThue", b =>
                {
                    b.HasOne("GearGo.Models.Entities.GioThue", "GioThue")
                        .WithMany("ChiTietGioThues")
                        .HasForeignKey("MaGioThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioThue");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("GearGo.Models.Entities.PhieuNhapHang", "PhieuNhapHang")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChinhSach", b =>
                {
                    b.HasOne("GearGo.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DanhMucSanPham", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DanhMucSanPham", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("MaDanhMucCha")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DonThue", b =>
                {
                    b.HasOne("GearGo.Models.Entities.ChinhSach", "ChinhSach")
                        .WithMany()
                        .HasForeignKey("MaChinhSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.TaiKhoan", "NguoiHuy")
                        .WithMany()
                        .HasForeignKey("MaNguoiHuy");

                    b.Navigation("ChinhSach");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiHuy");
                });

            modelBuilder.Entity("GearGo.Models.Entities.GioThue", b =>
                {
                    b.HasOne("GearGo.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("GearGo.Models.Entities.GiuCho", b =>
                {
                    b.HasOne("GearGo.Models.Entities.ChiTietDonThue", "ChiTietDonThue")
                        .WithOne("GiuCho")
                        .HasForeignKey("GearGo.Models.Entities.GiuCho", "MaChiTietDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDonThue");
                });

            modelBuilder.Entity("GearGo.Models.Entities.HinhAnhSanPham", b =>
                {
                    b.HasOne("GearGo.Models.Entities.SanPham", "SanPham")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("GearGo.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("GearGo.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMaiDanhMuc", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DanhMucSanPham", "DanhMucSanPham")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMaiDanhMucs")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucSanPham");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("GearGo.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GearGo.Models.Entities.LichSuTrangThaiDon", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DonThue", "DonThue")
                        .WithMany()
                        .HasForeignKey("MaDonThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.TaiKhoan", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("MaNguoiThucHien");

                    b.Navigation("DonThue");

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("GearGo.Models.Entities.LuotSuDungKhuyenMai", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DonThue", "DonThue")
                        .WithOne("LuotSuDungKhuyenMai")
                        .HasForeignKey("GearGo.Models.Entities.LuotSuDungKhuyenMai", "MaDonThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("LuotSuDungKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonThue");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("GearGo.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("GearGo.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("GearGo.Models.Entities.NhanVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("GearGo.Models.Entities.PhanCongThietBi", b =>
                {
                    b.HasOne("GearGo.Models.Entities.ChiTietDonThue", "ChiTietDon")
                        .WithMany()
                        .HasForeignKey("MaChiTietDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.NhanVien", "NhanVienHuy")
                        .WithMany()
                        .HasForeignKey("MaNhanVienHuy");

                    b.HasOne("GearGo.Models.Entities.NhanVien", "NhanVienPhanCong")
                        .WithMany()
                        .HasForeignKey("MaNhanVienPhanCong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDon");

                    b.Navigation("NhanVienHuy");

                    b.Navigation("NhanVienPhanCong");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("GearGo.Models.Entities.PhieuNhapHang", b =>
                {
                    b.HasOne("GearGo.Models.Entities.NhanVien", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("MaNguoiLap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGo.Models.Entities.NhanVien", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("MaNguoiXacNhan");

                    b.HasOne("GearGo.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiLap");

                    b.Navigation("NguoiXacNhan");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("GearGo.Models.Entities.SanPham", b =>
                {
                    b.HasOne("GearGo.Models.Entities.DanhMucSanPham", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ThietBi", b =>
                {
                    b.HasOne("GearGo.Models.Entities.ChiTietPhieuNhap", "ChiTietPhieuNhap")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaChiTietPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietDonThue", b =>
                {
                    b.Navigation("GiuCho");
                });

            modelBuilder.Entity("GearGo.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DanhMucSanPham", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("GearGo.Models.Entities.DonThue", b =>
                {
                    b.Navigation("ChiTietDonThues");

                    b.Navigation("LuotSuDungKhuyenMai");
                });

            modelBuilder.Entity("GearGo.Models.Entities.GioThue", b =>
                {
                    b.Navigation("ChiTietGioThues");
                });

            modelBuilder.Entity("GearGo.Models.Entities.KhuyenMai", b =>
                {
                    b.Navigation("KhuyenMaiDanhMucs");

                    b.Navigation("KhuyenMaiSanPhams");

                    b.Navigation("LuotSuDungKhuyenMais");
                });

            modelBuilder.Entity("GearGo.Models.Entities.PhieuNhapHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("GearGo.Models.Entities.SanPham", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("GearGo.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
